#!/usr/bin/python
### BEGIN INIT INFO
# Provides:          solid
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the Solid web interface
### END INIT INFO
import sys
import logging

try:
	import solid
except:
	print 'Solid is not installed'
	sys.exit()

import tornado.ioloop
import tornado.httpserver


from solid.web.libs.daemon import Daemon
from solid.web.server import application
from solid.core import settings

logging.basicConfig(filename=settings.LOGFILE,level=logging.ERROR)
PIDFILE = '/var/run/solid.pid'
logger = logging.getLogger('solid')

class SolidDaemon(Daemon):

	def run(self):
		server = tornado.httpserver.HTTPServer(application)
		server.bind(int(settings.WEB_APP['port']))
		server.start(0)
		tornado.ioloop.IOLoop.instance().start()

if __name__ == "__main__":

	daemon = SolidDaemon(PIDFILE)

	if len(sys.argv) == 2:
		if 'start' == sys.argv[1]:
			try:
				daemon.start()
			except:
				pass
		elif 'stop' == sys.argv[1]:
			print "Stopping Solid ..."
			daemon.stop()
		elif 'restart' == sys.argv[1]:
			print "Restaring Solid ..."
			daemon.restart()
		elif 'status' == sys.argv[1]:
			try:
				pf = file(PIDFILE,'r')
				pid = int(pf.read().strip())
				pf.close()
			except IOError:
				pid = None
			except SystemExit:
				pid = None

			if pid:
				print 'Solid {0} running as pid {1}'.format(Solid.__version__, pid)
				print 'You can check it out at {0}:{1}'.format(settings.WEB_APP['host'],
						settings.WEB_APP['port'])
			else:
				print 'Solid is not running.'

		else:
			print "Unknown command"
			sys.exit(2)
			sys.exit(0)
	else:
		print "usage: %s start|stop|restart|status" % sys.argv[0]
		sys.exit(2)

